from project.controller import Controller


# aquarium1 = SaltwaterAquarium('Aqua1')
# aquarium2 = SaltwaterAquarium('Aqua2')
# aquarium3 = FreshwaterAquarium('Aqua3')
# aquarium4 = FreshwaterAquarium('Aqua4')
# fish1 = SaltwaterFish('Fish1', 'Sharan', 5)
# fish2 = SaltwaterFish('Fish2', 'Sharan2', 6)
# fish3 = FreshwaterFish('Fish3', 'Karakuda', 8)
# fish4 = FreshwaterFish('Fish4', 'Barakuda', 9)
# decoration1 = Ornament()
# decoration2 = Ornament()
# decoration3 = Plant()
# decoration4 = Plant()
new_controller = Controller()
print(new_controller.add_aquarium('SaltwaterAquarium', 'Aqua1'))
print(new_controller.add_aquarium('FreshwaterAquarium', 'Aqua2'))
print(new_controller.add_fish('Aqua1', 'SaltwaterFish', 'Sharan1', 'Barakuda', 5))
print(new_controller.add_fish('Aqua1', 'SaltwaterFish', 'Sharan2', 'Barakuda', 5))
print(new_controller.add_fish('Aqua1', 'SaltwaterFish', 'Sharan3', 'Barakuda', 5))
print(new_controller.add_fish('Aqua2', 'FreshwaterFish', 'Karakuda1', 'Lefer', 6))
print(new_controller.add_fish('Aqua2', 'FreshwaterFish', 'Karakuda2', 'Lefer', 6))
print(new_controller.add_fish('Aqua2', 'FreshwaterFish', 'Karakuda3', 'Lefer', 6))
print(new_controller.add_decoration('Ornament'))
print(new_controller.add_decoration('Ornament'))
print(new_controller.add_decoration('Plant'))
print(new_controller.add_decoration('Ornament'))
print(new_controller.add_decoration('Ornament'))
print(new_controller.add_decoration('Plant'))
print(new_controller.insert_decoration('Aqua1', 'Ornament'))
print(new_controller.insert_decoration('Aqua1', 'Ornament'))
print(new_controller.insert_decoration('Aqua1', 'Ornament'))
print(new_controller.insert_decoration('Aqua1', 'Ornament'))
print(new_controller.insert_decoration('Aqua1', 'Plant'))
print(new_controller.insert_decoration('Aqua1', 'Plant'))
print(new_controller.feed_fish('Aqua1'))
print(new_controller.feed_fish('Aqua1'))
print(new_controller.feed_fish('Aqua1'))
# print(str(new_controller.aquariums[0]))
print(new_controller.report())
print(new_controller.calculate_value('Aqua1'))
print(new_controller.add_fish('Aqua2', 'FreshwaterFish', 'Sharan1', 'Barakuda', 5))
print(new_controller.insert_decoration('Aqua1', 'Diamond'))
